# Submitted by Tushar Mitra, batch of 29th May

Q1. Mention some of the advantages of python?


Ans. Python is an easy to understand and learn programming language and has a lot of libraries which we can import to perform endless tasks like machine learning, data science and implement AI models. It is also free to use and is open source which gives it a little advantage over other programming languages.


Q2. What are local variables and global variables in Python?

Ans. Local variables are variables that are declared within a particular scope, e.g. a function and are accessible only there. Global variables on the other hand are accessible throughout the program as they are declared outside any local scope.

For Example:-


```
a=5

def func:
  b=7
  return
```

Here a is a global variable and can be accessed anywhere, including in the function func, whereas b is a local variable and is local to the function func, i.e. it can be accessed only within func.

Q3. What is Lambda Functions in Python?

Ans. Lambda functions in Python are small, anonymous functions used to create simple, one-line functions without a formal function definition. They are also known as anonymous functions because they do not require a specific name like regular functions defined using the def keyword.

For Example:-


```
c=lambda a,b : a+b
c(6,3)
```
The output will be 9 as this lambda function adds the given two arguments.


Q4. What is a Negative Index in Python?

Ans. Negative index is index from the last element of the object we are indexing instead of the first. So, for example if we have a list a = [10,22,13,44,65], then a[-1] will give us 65 and a[-2] will give us 44.

Q5. What is the difference between tuples and lists?

Ans. Tuples and lists are data structures in Python used to store collections of items. The key difference between them lies in their mutability. Tuples are immutable, meaning their elements cannot be changed after creation, while lists are mutable, allowing for modification of elements. Tuples are defined using parentheses, and once created, their size and content remain fixed. Lists, defined with square brackets, can grow or shrink as needed. Tuples are memory-efficient and have slightly better performance due to their immutability. Lists are commonly used for dynamic collections that require modifications, while tuples are preferred for fixed collections with constant elements.

Also, tuples are denoted by () and lists by [].

Q6. What is a dynamically typed language?

A dynamically typed language is one where the data type of a variable is determined automatically when the program is run, rather than the programmer explicitly providing the data type of the variable they are declaring.

Python is an example. e.g. if in Python we write a = "abcd", then the data type of a is automatically determined as string, rather than us having to state that.

Q7. What are the data types available in python? Brief about it?

In Python, there are several built-in data types that are used to represent different kinds of values. Here's a brief overview of the main data types available in Python:

1.Numeric Types:

int: Represents integer numbers without decimal points.
float: Represents floating-point numbers with decimal points.
complex: Represents complex numbers in the form of a + bj, where a and b are floats, and j is the imaginary unit.

2.Boolean Type:

bool: Represents boolean values True or False.

3.Sequence Types:

str: Represents strings of characters, which are immutable sequences of Unicode characters.
list: Represents ordered, mutable sequences of elements. Lists are enclosed in square brackets [].
tuple: Represents ordered, immutable sequences of elements. Tuples are enclosed in parentheses ().

4.Set Types:

set: Represents an unordered collection of unique elements. Sets are enclosed in curly braces {}.
frozenset: Represents an immutable set, similar to a set but cannot be modified after creation. Frozensets are enclosed in curly braces {}.

5.Mapping Type:

dict: Represents associative arrays or dictionaries, consisting of key-value pairs. Dictionaries are enclosed in curly braces {} and have keys and corresponding values separated by colons :

6.None Type:

None: Represents the absence of a value, similar to null in other programming languages. It is often used to indicate that a variable has no value or has not been initialized.

Q8. Why we have to use functions in Python? Explain with an example?

Ans. We need to use functions for tasks that we have to perform again and again, so that we do not need to retype the same code every time but can call the corresponding function instead.

e.g. the following function combines the two lists given to it and returns the resulting list.

In [12]:
def combine_lists (a,b):
  c=list()
  for i in a:
    c.append(i)
  for i in b:
    c.append(i)
  return c

a=[1,2,3]
b=['a','b','c']
c=combine_lists(a,b)
c

[1, 2, 3, 'a', 'b', 'c']

Q9. What is the difference between function and generators? Give an example?

Ans. Generators are like functions but instead of return they use yield, which appends elements to the generator object which is then returned. We can use for loop to iterate through the returned generator object.

They are advantageous over functions when the input is very large, as functions will take a lot of time and memory but generators will display the output in the console only, consuming much lesser time and memory. Functions will compute the entire thing before returning, but generators will go one element at a time.

e.g.


```
def gen(n):
  for i in range(n):
    yield i
```

This generator will generate a sequence of the first n whole numbers



In [13]:
def gen(n):
  for i in range(n):
    yield i

a = gen(5)
for i in a:
  print (i)

0
1
2
3
4


Q10. Explain brief about conditional statements with an example?

Ans. Conditional statements are statements that check whether or not the given condition is true, and based on whether it is true or false, it runs the corresponding block of code.

e.g. in the following code the conditional statement checks the condition a < 5. As a is 10, so the condition is false, and it goes to the 'else' part and computes that. If it was true it would have computed the first block instead.

In [14]:
a = 10
if (a<5):
  print('This prints if the statement is true')
else:
  print('This prints if the statement is false')

This prints if the statement is false


Q11. Why we have to use exceptional handling in python? What are the keyword used to handle the error , give one example?

Exception handling is an essential concept in Python and other programming languages because it allows developers to gracefully handle unexpected or exceptional situations that may occur during program execution. When an error or exceptional event occurs in Python, it can disrupt the normal flow of the program and cause it to terminate abruptly. Exception handling helps avoid such abrupt terminations and enables developers to take appropriate actions when errors occur, ensuring the program can recover or gracefully handle the situation.

The main keywords used for exception handling in Python are:

try: This block is used to enclose the code that might raise an exception or error.

except: This block is used to handle the exception that is raised in the try block. It specifies what actions to take if a specific exception occurs.

else: This block is executed if there is no exception in the try block.

finally: This block is executed regardless of whether an exception occurs or not. It is often used for cleanup tasks that must be performed, such as closing files or releasing resourceswhile True:
  try:
    a=int(input('Dividend: '))
    b=int(input('Divisor: '))
    print(a,'/2',b,'=',a/b)
    break
  except:
    print('Error. Try again')


Q12. Define class and objects with an example?

Ans. Classes are user defined data types that can have their own members and functions, which can be used to keep related functions together and data together for a specific purpose. e.g. we can make a student class which can have student details as members, e.g. name and email, along with functions like register for a course, etc.

Objects are instances of classes. Thus, if we define the student class described above and then make a variable of student type, then that variable is an object of student type.

e.g.

In [15]:
class student:
    def __init__(self, name, email):
        self.name = name
        self.email = email

s = student('Tushar', 'abc@xyz.com')
print(s.name, s.email)


Tushar abc@xyz.com


In [16]:
print('Q13. Write a program to swap the two numbers in python?')

a=5
b=10
print('Before: a = ',a,", b = ",b)
(a,b)=(b,a)
print('After: a = ',a,'b = ',b)

Q13. Write a program to swap the two numbers in python?
Before: a =  5 , b =  10
After: a =  10 b =  5


In [17]:
print('Q14. Write a palindrome program in python')

def palindrome (a):
  l=len(a)
  for i in range(l):
    if a[i]!=a[l-i-1]:
      return False
  return True

print(palindrome('abcabca'))
print(palindrome('abcba'))
print(palindrome('abbba'))

Q14. Write a palindrome program in python
False
True
True


Q15. What is the use of numpy array over list?

Ans. 1. Numpy takes lesser memory than lists.
2. Numpy is more convenient. For e.g., we can directly add two numpy arrays while we have to use list comprehension in the case of lists
3. Numpy is faster than lists

Q16. Explain in brief about reshape in numpy with an example?

Ans. Reshape changes the dimensions of the numpy array into the given dimensions. For example, the following code changes the given array from a 4x4 array to a 8x2 array.

In [18]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(a,'\n')

a=np.reshape(a,(8,2))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


Q17. What is the use of pandas explain in brief?

Ans.Pandas is a popular Python library used for data manipulation and analysis. In short and simple words, Pandas is used for:

1.Reading and writing data: It allows you to read data from various file formats like CSV, Excel, and SQL databases, and write data back to these formats.

2.Data cleaning and preprocessing: It provides powerful tools for handling missing data, removing duplicates, and transforming data into a suitable format for analysis.

3.Data manipulation: Pandas allows you to filter, sort, group, and aggregate data, enabling you to extract meaningful insights and summaries from large datasets.

4.Data analysis and visualization: It supports various statistical operations and integrates well with other libraries like Matplotlib and Seaborn for data visualization.

5.Time series data handling: Pandas has excellent support for working with time series data, making it valuable in finance, economics, and other time-dependent domains.



Q18. What do you mean by supervised machine learning and unsupervised machine learning? Explain in brief?

Ans.Supervised Machine Learning: In supervised learning, the model is trained on labeled data, where the input data is paired with corresponding output labels. The goal is for the model to learn the mapping between inputs and outputs, so it can make accurate predictions on new, unseen data. Examples include image classification (where images are labeled with their corresponding categories) and predicting house prices (where features like size, location, etc., are used to predict the price).

Unsupervised Machine Learning: In unsupervised learning, the model is trained on unlabeled data, and it tries to identify patterns or structures within the data without specific guidance. The goal is to discover hidden relationships or groupings in the data. Examples include clustering customer data to segment them into different groups based on behavior patterns or reducing the dimensionality of data for visualization or compression purposes.

Q19. Differenciate between Decision tree and Random forest?

Ans. A decision tree is the basic unit of a random forest.

A decision tree is a structure in the form of one root nodes, several decision nodes and leaf nodes that contain the final output. We start from the root node, follow the branch that satisifies our condition and continue till we reach a leaf node, that contains the output.

A random forest on the other hand is a collection of several decision trees.

Q20. What do you mean by forward propagation and backward propagation in ANN?

Ans. Forward propagation in an ANN is when we move forward, i.e. left to right, i.e. towards the direction of the output layer.

Backward propagation is when we move in the opposite direction, towards the input layer, i.e. the output of a hidden layer or the output layer itself is used as the input in a previous layer. This is done to update weights and reduce loss.

Q21. Explain the working flow of ANN and CNN?

Ans. ANN consists of input layer, hidden layers, activation functions, bias, weights and output layer.

We start from the input layer, that adds all the inputs multiplied by their weights, adds the bias and uses the activation function to produce an output which goes on to the next layer, and so on, until we reach the final output layer. During this process we also update weights to reduce loss.

CNN consists of an input image, that goes through optional padding. Then several rounds (as required) of convolution, and pooling happen along with filters, to produce a fully connected layer. Then the output produced is flattened. This flattened image is used as input to the fully connected layer to produce a final output which could be a classification of the original image.

Q22. What is the use of activation function and optimizers?

Ans. Activation Function: Activation functions are used in neural networks to introduce non-linearity to the model. They decide whether a neuron should be activated (fired) or not based on the input. Activation functions help the neural network learn complex patterns and relationships in the data, making it capable of solving more sophisticated problems.

Optimizers: Optimizers are algorithms used in training neural networks to minimize the error and improve the model's performance. They adjust the model's parameters (weights and biases) during the training process to find the best combination that minimizes the difference between predicted and actual values. Optimizers play a vital role in speeding up convergence and ensuring the neural network learns efficiently. They help in finding the global or local minimum of the loss function, which indicates the best possible fit for the data.

Q23. What is the difference between R square and adjusted Rsquare?

Ans. In short and simple words:

R-squared (R²) is a statistical measure that represents the proportion of variance in the dependent variable explained by the independent variables in a regression model. It tells us how well the model fits the data.

Adjusted R-squared (adjusted R²) is a modification of R-squared that accounts for the number of independent variables in the model. It penalizes the addition of unnecessary variables, helping to prevent overfitting. Adjusted R-squared increases only if the additional variable improves the model more than would be expected by chance. It provides a more accurate assessment of the model's goodness of fit when there are multiple independent variables.

Q24. What do you mean by LSTM in RNN?

Ans.LSTM stands for Long Short-Term Memory, and it is a type of Recurrent Neural Network (RNN) architecture. In simple words, LSTM is designed to handle long sequences of data and retain important information over time. It is particularly useful for tasks that involve analyzing and making predictions based on sequences of data, such as natural language processing, speech recognition, and time series forecasting. LSTM's unique design allows it to effectively capture dependencies and patterns in sequential data, making it a powerful tool for handling time-based information in machine learning and artificial intelligence applications

Q25. What is the use of image processing?

Ans. Image processing is used to analyze, modify, and enhance digital images. It helps in tasks like recognizing objects, improving image quality, compressing images for storage and transmission, and enabling applications in fields like medical imaging, surveillance, and computer vision. In simple terms, it allows computers to understand and work with images, making it a valuable tool in various industries and applications.

Q26. What are the steps involved in NLP?

Ans. The steps involved in natural language processing are:

1. Lexical analysis
2. Syntactical analysis
3. Semantic analysis
4. Discourse integration
5. Pragmatic analysis

Q27. What do you mean by bias and variance?

Ans. Bias is the model error that happens due to under fitting, or not viewing the data enough times to draw correct patterns from it.

Variance on the other hand happens with over fitting, when the data is viewed too many times and results in the model being very accurate with the training data but failing with new data.

Q28. What are the steps involved in machine learning to create model?

Ans.Creating a machine learning model involves several essential steps to ensure its effectiveness and accuracy. Here are the main steps involved in building a machine learning model:

1.Data Collection: Gather relevant data from various sources, which will be used to train and evaluate the model.

2.Data Preprocessing: Clean, transform, and prepare the data for training. This involves handling missing values, scaling features, and converting categorical variables into numerical representations.

3.Feature Engineering: Select or create the most relevant features from the data that will have the most significant impact on the model's performance.

4.Splitting Data: Divide the data into two parts: a training set (used to train the model) and a test set (used to evaluate the model's performance).

5.Choosing a Model: Select the appropriate machine learning algorithm or model that best suits the nature of the problem and the type of data.

6.Training the Model: Use the training set to teach the model to recognize patterns and relationships in the data.

7.Model Evaluation: Assess the model's performance on the test set to measure how well it generalizes to unseen data.

8.Hyperparameter Tuning: Fine-tune the model by adjusting hyperparameters to optimize its performance.

9.Model Deployment: Once the model performs well, deploy it to make predictions on new, real-world data.

10.Monitoring and Maintenance: Continuously monitor the model's performance and update it as necessary to ensure it remains accurate and relevant over time.

